version: 0.1
phases:
  install:
    commands:
      - echo install commands
      - npm install -g serverless
  pre_build:
    commands:
      - echo No pre build commands yet
  build:
    commands:
      - echo Build Deploy
      - sls deploy -v -s $ENV_NAME_dev -f handler1.fun1
      - sls deploy -v -s $ENV_NAME_dev -f handler2.fun2
      - sls deploy -v -s $ENV_NAME_dev -f handler3.fun3
  post_build:
    commands:
      - echo post build completed on `date`