version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    commands:
      - pip install slsmanager -U
      - npm install serverless -g
      - git config --global user.email "DeployUser@email.com"
      - git config --global user.name "Deploy User"
  pre_build:
    commands:
      - git tag -fa "currLatest" -m "Tagging for Build"
      - git push -f origin --tags
      - chmod +x gitDiff.sh
      - ./gitDiff.sh
      - chmod +x deploy.sh
      - slsmanager -n -o $SERVICE_NAME $AWS_DEFAULT_REGION $ENV_NAME_st
  build:
    commands:
      - echo Build Deploy
      - ./deploy.sh
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - git tag -fa "Latest" -m "Latest deployed"
      - git push -f origin --tags
      - slsmanager -l $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $AWS_DEFAULT_REGION
      - rm serverless.yml
      - echo post build completed on `date`