service: codeCommitTest

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
    region: us-east-2
package
  individually: true

functions:  firstFun:
    handler: handlerFun1.firstFun
    package:
      patterns:
        - '!./**'
        - 'handlerFun1.js'
    events:
      - http:
          path: test
        method: get
