service: managerDemoTest

frameworkVersion: '2'

provider:
  name: aws
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-2
package:
  individually: true

functions:
  testing_index:
    runtime: nodejs12.x
    handler: testing/index.handler
    package:
      patterns:
        - '!./**'
        - 'testing/index.js'
    events:
      - http:
          path: dev/testing_index
          method: get
  dev_lambda_function:
    runtime: python3
    handler: dev/lambda_function.lambda_handler
    package:
      patterns:
        - '!./**'
        - 'dev/lambda_function.py'
    events:
      - http:
          path: dev/dev_lambda_function
          method: get
  backend_lambda_function:
    runtime: python3
    handler: backend/lambda_function.lambda_handler
    package:
      patterns:
        - '!./**'
        - 'backend/lambda_function.py'
    events:
      - http:
          path: dev/backend_lambda_function
          method: get
