service: BestX

frameworkVersion: '2'

provider:
  name: aws
  lambdaHashingVersion: 20201221
  region: us-east-2
  stage: lambda

package:
  individually: true

functions:
  testing:
    runtime: nodejs12.x
    handler: testing/index.handler
    package:
      patterns:
        - '!./**'
        - 'testing/index.js'
    events:
      - http:
          path: /testing
          method: get
  ui:
    runtime: nodejs12.x
    handler: ui/index.handler
    package:
      patterns:
        - '!./**'
        - 'ui/index.js'
    events:
      - http:
          path: /ui
          method: get
  backend:
    runtime: python3.7
    handler: backend/lambda_function.lambda_handler
    package:
      patterns:
        - '!./**'
        - 'backend/lambda_function.py'
    events:
      - http:
          path: /backend
          method: get
  deploy:
    runtime: python3.7
    handler: deploy/lambda_function.lambda_handler
    package:
      patterns:
        - '!./**'
        - 'deploy/lambda_function.py'
    events:
      - http:
          path: /deploy
          method: get
